version: '3.9'

services:
  archivo:
    image: archivo-api
    container_name: archivo-container 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - archivo-network
    depends_on:
      - mysql
    entrypoint: ["sh", "-c", "while ! nc -z mysql 3306; do sleep 1; done; java -jar /root/target/archivo-0.0.1-SNAPSHOT.jar"]

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: archivo
      MYSQL_USER: archivo_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    networks:
      - archivo-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  archivo-network:

volumes:
  mysql-volume:
